In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import torch

In [6]:
from torch import nn
from torch.utils.data import DataLoader
from torchvision import datasets
from torchvision.transforms import ToTensor

## Load dataset

In [18]:
df_zillow = pd.read_csv('../data/zillow_cleaned.csv')
df_zillow

,Unnamed: 0,zpid,address,price,beds,baths,area_sqft,latitude,longitude,status,...,zestimate,detail_url,has_open_house,is_featured,street_add,city,state_zipcode,state_code,zipcode,state_name
0,0,17264897,"979 Kevin Ave, Redlands, CA 92373",447000,3.0,2.0,1300.0,34.040520,-117.186195,House for sale,...,455500.0,https://www.zillow.com/homedetails/979-Kevin-A...,False,False,979 Kevin Ave,Redlands,CA 92373,CA,92373,California
1,1,20021372,"13114 Addison St, Sherman Oaks, CA 91423",2795000,4.0,5.0,2900.0,34.160885,-118.418770,House for sale,...,NaN,https://www.zillow.com/homedetails/13114-Addis...,True,False,13114 Addison St,Sherman Oaks,CA 91423,CA,91423,California
2,2,20009320,"6032 Goodland Ave, North Hollywood, CA 91606",1718000,4.0,3.0,3025.0,34.180450,-118.411280,House for sale,...,1695500.0,https://www.zillow.com/homedetails/6032-Goodla...,False,False,6032 Goodland Ave,North Hollywood,CA 91606,CA,91606,California
3,3,460204882,"3325 Tonopah St, Oceanside, CA 92054",899999,3.0,3.0,1682.0,33.214260,-117.341500,Coming soon,...,NaN,https://www.zillow.com/homedetails/3325-Tonopa...,False,False,3325 Tonopah St,Oceanside,CA 92054,CA,92054,California
4,4,20769150,"963 Pine Grove Ave, Los Angeles, CA 90042",995000,2.0,2.0,1271.0,34.132890,-118.186220,House for sale,...,999900.0,https://www.zillow.com/homedetails/963-Pine-Gr...,False,False,963 Pine Grove Ave,Los Angeles,CA 90042,CA,90042,California
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2154,2209,460202745,"111 Beechwood Ests, Scott Depot, WV 25560",499900,5.0,3.0,3651.0,38.444412,-81.925500,House for sale,...,NaN,https://www.zillow.com/homedetails/111-Beechwo...,True,False,111 Beechwood Ests,Scott Depot,WV 25560,WV,25560,West Virginia
2155,2210,23058172,"390 Dolly Ln, Dryfork, WV 26263",199000,2.0,1.0,1000.0,38.971350,-79.404600,House for sale,...,192800.0,https://www.zillow.com/homedetails/390-Dolly-L...,False,False,390 Dolly Ln,Dryfork,WV 26263,WV,26263,West Virginia
2156,2211,22336003,"1107 New York Ave, Martinsburg, WV 25401",249900,3.0,2.0,984.0,39.446636,-77.976555,House for sale,...,247600.0,https://www.zillow.com/homedetails/1107-New-Yo...,False,False,1107 New York Ave,Martinsburg,WV 25401,WV,25401,West Virginia
2157,2212,22907826,"2009 Ices Ferry Dr, Morgantown, WV 26508",1195000,5.0,5.0,5945.0,39.661613,-79.846214,House for sale,...,1103700.0,https://www.zillow.com/homedetails/2009-Ices-F...,False,False,2009 Ices Ferry Dr,Morgantown,WV 26508,WV,26508,West Virginia
2158,2213,212253246,"2311 Summit Point Rd, Summit Point, WV 25446",383000,3.0,2.0,1200.0,39.244170,-77.968500,House for sale,...,NaN,https://www.zillow.com/homedetails/2311-Summit...,False,False,2311 Summit Point Rd,Summit Point,WV 25446,WV,25446,West Virginia

In [19]:
# Drop irrelevant/duplicate columns
df_zillow.drop(inplace=True, columns=[
    'detail_url',
    'address',
    'zpid',
    'Unnamed: 0',
    'street_add',
    'state_zipcode',
])

df_zillow

,price,beds,baths,area_sqft,latitude,longitude,status,home_type,days_on_zillow,zestimate,has_open_house,is_featured,city,state_code,zipcode,state_name
0,447000,3.0,2.0,1300.0,34.040520,-117.186195,House for sale,SINGLE_FAMILY,5,455500.0,False,False,Redlands,CA,92373,California
1,2795000,4.0,5.0,2900.0,34.160885,-118.418770,House for sale,SINGLE_FAMILY,8,NaN,True,False,Sherman Oaks,CA,91423,California
2,1718000,4.0,3.0,3025.0,34.180450,-118.411280,House for sale,SINGLE_FAMILY,8,1695500.0,False,False,North Hollywood,CA,91606,California
3,899999,3.0,3.0,1682.0,33.214260,-117.341500,Coming soon,SINGLE_FAMILY,4,NaN,False,False,Oceanside,CA,92054,California
4,995000,2.0,2.0,1271.0,34.132890,-118.186220,House for sale,SINGLE_FAMILY,5,999900.0,False,False,Los Angeles,CA,90042,California
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2154,499900,5.0,3.0,3651.0,38.444412,-81.925500,House for sale,SINGLE_FAMILY,4,NaN,True,False,Scott Depot,WV,25560,West Virginia
2155,199000,2.0,1.0,1000.0,38.971350,-79.404600,House for sale,SINGLE_FAMILY,23,192800.0,False,False,Dryfork,WV,26263,West Virginia
2156,249900,3.0,2.0,984.0,39.446636,-77.976555,House for sale,SINGLE_FAMILY,27,247600.0,False,False,Martinsburg,WV,25401,West Virginia
2157,1195000,5.0,5.0,5945.0,39.661613,-79.846214,House for sale,SINGLE_FAMILY,224,1103700.0,False,False,Morgantown,WV,26508,West Virginia
2158,383000,3.0,2.0,1200.0,39.244170,-77.968500,House for sale,SINGLE_FAMILY,101,NaN,False,False,Summit Point,WV,25446,West Virginia

In [21]:
df_zillow = pd.get_dummies(df_zillow)
df_zillow

,price,beds,baths,area_sqft,latitude,longitude,days_on_zillow,zestimate,has_open_house,is_featured,...,state_name_Oklahoma,state_name_Pennsylvania,state_name_South Carolina,state_name_Tennessee,state_name_Texas,state_name_Vermont,state_name_Virginia,state_name_Washington,state_name_West Virginia,state_name_Wisconsin
0,447000,3.0,2.0,1300.0,34.040520,-117.186195,5,455500.0,False,False,...,False,False,False,False,False,False,False,False,False,False
1,2795000,4.0,5.0,2900.0,34.160885,-118.418770,8,NaN,True,False,...,False,False,False,False,False,False,False,False,False,False
2,1718000,4.0,3.0,3025.0,34.180450,-118.411280,8,1695500.0,False,False,...,False,False,False,False,False,False,False,False,False,False
3,899999,3.0,3.0,1682.0,33.214260,-117.341500,4,NaN,False,False,...,False,False,False,False,False,False,False,False,False,False
4,995000,2.0,2.0,1271.0,34.132890,-118.186220,5,999900.0,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2154,499900,5.0,3.0,3651.0,38.444412,-81.925500,4,NaN,True,False,...,False,False,False,False,False,False,False,False,True,False
2155,199000,2.0,1.0,1000.0,38.971350,-79.404600,23,192800.0,False,False,...,False,False,False,False,False,False,False,False,True,False
2156,249900,3.0,2.0,984.0,39.446636,-77.976555,27,247600.0,False,False,...,False,False,False,False,False,False,False,False,True,False
2157,1195000,5.0,5.0,5945.0,39.661613,-79.846214,224,1103700.0,False,False,...,False,False,False,False,False,False,False,False,True,False
2158,383000,3.0,2.0,1200.0,39.244170,-77.968500,101,NaN,False,False,...,False,False,False,False,False,False,False,False,True,False

In [26]:
df_zillow = df_zillow.astype('float64')
df_zillow

,price,beds,baths,area_sqft,latitude,longitude,days_on_zillow,zestimate,has_open_house,is_featured,...,state_name_Oklahoma,state_name_Pennsylvania,state_name_South Carolina,state_name_Tennessee,state_name_Texas,state_name_Vermont,state_name_Virginia,state_name_Washington,state_name_West Virginia,state_name_Wisconsin
0,447000.0,3.0,2.0,1300.0,34.040520,-117.186195,5.0,455500.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2795000.0,4.0,5.0,2900.0,34.160885,-118.418770,8.0,NaN,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,1718000.0,4.0,3.0,3025.0,34.180450,-118.411280,8.0,1695500.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,899999.0,3.0,3.0,1682.0,33.214260,-117.341500,4.0,NaN,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,995000.0,2.0,2.0,1271.0,34.132890,-118.186220,5.0,999900.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2154,499900.0,5.0,3.0,3651.0,38.444412,-81.925500,4.0,NaN,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2155,199000.0,2.0,1.0,1000.0,38.971350,-79.404600,23.0,192800.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2156,249900.0,3.0,2.0,984.0,39.446636,-77.976555,27.0,247600.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2157,1195000.0,5.0,5.0,5945.0,39.661613,-79.846214,224.0,1103700.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2158,383000.0,3.0,2.0,1200.0,39.244170,-77.968500,101.0,NaN,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

In [28]:
tensor = torch.from_numpy(df_zillow.values)
tensor.shape

torch.Size([2159, 2707])

## Build NN Model

In [7]:
device = torch.accelerator.current_accelerator().type if torch.accelerator.is_available() else "cpu"
print(f"Using {device} device")

Using mps device

In [22]:
# Define model
class NeuralNetwork(nn.Module):
    def __init__(self):
        super().__init__()
        self.flatten = nn.Flatten()
        self.linear_relu_stack = nn.Sequential(
            nn.Linear(28*28, 512),
            nn.ReLU(),
            nn.Linear(512, 512),
            nn.ReLU(),
            nn.Linear(512, 10)
        )

    def forward(self, x):
        x = self.flatten(x)
        logits = self.linear_relu_stack(x)
        return logits

model = NeuralNetwork().to(device)
print(model)

NeuralNetwork(
  (flatten): Flatten(start_dim=1, end_dim=-1)
  (linear_relu_stack): Sequential(
    (0): Linear(in_features=784, out_features=512, bias=True)
    (1): ReLU()
    (2): Linear(in_features=512, out_features=512, bias=True)
    (3): ReLU()
    (4): Linear(in_features=512, out_features=10, bias=True)
  )
)